dist: bionic
language: python
python:
  - 3.8
  - 3.9
matrix:
  fast_finish: true
  include:
    - python: 3.8

before_install:
  - sudo apt-get update  && sudo apt-get install  python3-pip asymptote llvm-10 llvm-10-dev
  - python --version
  - pip3 install numpy
  - pip3 install git+https://github.com/mmatera/mathics
  - pip3 install ipywidgets
  - pip3 install ipykernel
  - pip3 install metakernel
  - pip3 install jupyter_kernel_test
  - pip3 install unittest2
  - python -m pip install -e git://github.com/mathics/Mathics.git#egg=Mathics3
  - python -m pip install -e git://github.com/Mathics3/pymathics-asy#egg=pymathics-asy
install:
  - python setup.py install
script:
  - python test.py
notifications:
email: false
