name: Mathics (ubuntu)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/mmatera/mathics
        pip install ipywidgets
        pip install ipykernel
        pip install metakernel
        pip install jupyter_kernel_test
        pip install unittest2
        pip install -e git://github.com/Mathics3/pymathics-asy#egg=pymathics-asy
    - name: Install Mathics
      run: |
        pip install -e .
    - name: Test Mathics
      run: |
        pip install pytest pexpect
        make -j3 check
